In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
print(np_array)

[[1 2]
 [3 4]]


In [14]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [15]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.8357, 0.5256],
        [0.5729, 0.0455]]) 



In [16]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [18]:
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7519, 0.5978, 0.2113],
        [0.6590, 0.0832, 0.4252]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [20]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [21]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [23]:
tensor = torch.ones(4,3)
print('First row: ', tensor[0])
print('First column: ', tensor[:,0])
print('Last column:', tensor[..., -1])
tensor[:,1]=0
print(tensor)

First row:  tensor([1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


In [24]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.]])


In [25]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)

# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


C:\Users\X7\AppData\Local\Temp/ipykernel_10424/1324593906.py:6: UserWarning: An output with one or more elements was resized since it had shape [4, 3], which does not match the required output shape [4, 4].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ..\aten\src\ATen\native\Resize.cpp:23.)
  torch.matmul(tensor, tensor.T, out=y3)


In [27]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

8.0 <class 'float'>


In [29]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]]) 

tensor([[6., 5., 6.],
        [6., 5., 6.],
        [6., 5., 6.],
        [6., 5., 6.]])


In [30]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [31]:
n = np.ones(5)
t = torch.from_numpy(n)

In [32]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
